SER-615: Totally weird, but it looks like the pdf generator classes need to be classes instead of objects. Otherwise, in production we see a "NoClassDefFoundError: Could not initialize class services.pdf.EgraphExplanationPdf". So, switching EgraphExplanationPdf and GiftCertificatePdf to case classes.